# AAIRE MVP Configuration - As per SRS v2.0
system:
  name: "AAIRE"
  version: "1.0-MVP"
  environment: "development"
  
# Compliance Rules - MVP-FR-017, MVP-FR-018
compliance_rules:
  - pattern: "tax.*advice|tax.*planning|minimize.*tax"
    response: "I can explain accounting treatments but cannot provide tax advice. Please consult a tax professional."
    log_level: "warning"
    
  - pattern: "legal.*advice|lawsuit|sue|legal.*interpretation"
    response: "I can explain standards but cannot provide legal interpretations. Please consult legal counsel."
    log_level: "warning"
    
  - pattern: "investment.*advice|buy.*sell|trading"
    response: "I provide accounting guidance only, not investment advice."
    log_level: "warning"
    
  - pattern: "dinner|food|eat|recipe|cooking|restaurant|meal|lunch|breakfast|hungry|diet|nutrition"
    response: "I'm AAIRE, your insurance and accounting assistant. I can help you with insurance accounting standards (US GAAP, IFRS), actuarial analysis, regulatory compliance, and financial reporting questions. Please ask me about topics related to insurance, accounting, or actuarial matters."
    log_level: "info"
    
  - pattern: "weather|sports|entertainment|movie|music|game|vacation|travel|personal|relationship|health|medical|politics"
    response: "I specialize in insurance accounting and actuarial topics. I can assist you with questions about insurance reserves, LICAT ratios, IFRS 17, US GAAP standards, regulatory compliance, actuarial calculations, and financial reporting. How can I help you with your insurance or accounting needs?"
    log_level: "info"

# Chunking Strategies - Hierarchical per MVP requirements
chunking_strategies:
  default:
    type: "hierarchical"
    chunk_size: 1024
    overlap: 150
    preserve: ["headers", "lists", "tables"]
    
  table_aware:
    type: "specialized"
    preserve_structure: true
    max_size: 1000
    
  actuarial_tables:
    type: "table_specialized"
    preserve_formulas: true
    chunk_size: 800

# Retrieval Configuration - MVP-FR-014
retrieval_config:
  similarity_threshold: 0.65
  max_results: 20
  use_cache: true
  cache_ttl: 3600
  reranking_enabled: false  # Disabled for MVP

# LLM Configuration
llm_config:
  provider: "openai"
  model: "gpt-4o-mini"  # Default model (override with OPENAI_MODEL env var)
  fallback: "gpt-4o-mini"  # Fallback model - same as primary for consistency
  temperature: 0.1  # Low temperature for consistent responses
  max_tokens: 6000  # Increased for better context and conversation history
  
# Conversation History Settings
conversation_config:
  max_history_messages: 20  # Keep last 20 messages (10 exchanges)
  max_message_length: 500   # Allow longer message context
  context_window_tokens: 8000  # GPT-4o-mini supports 128k context
  
# Embedding Configuration
embedding_config:
  model: "text-embedding-ada-002"
  dimensions: 1536
  batch_size: 100

# Performance Settings
performance:
  query_timeout: 30
  max_concurrent_queries: 100
  response_time_target: 3.0  # seconds p95